var CARDS_PREFIX = 'spanish-';
var CARDS_DATA =
[{"id":"cuerpo-body","category":"body","question":"'the body'","answer":"el cuerpo"},
{"id":"pelo-hair","category":"body","question":"'the hair'","answer":"el pelo"},
{"id":"nariz-nose","category":"body","question":"'the nose'","answer":"el nariz"},
{"id":"labio-lip","category":"body","question":"'the lip'","answer":"el labio"},
{"id":"diente-tooth","category":"body","question":"'the tooth'","answer":"el diente"},
{"id":"cuello-neck","category":"body","question":"'the neck'","answer":"el cuello"},
{"id":"hombro-shoulder","category":"body","question":"'the shoulder'","answer":"el hombro"},
{"id":"brazo-arm","category":"body","question":"'the arm'","answer":"el brazo"},
{"id":"codo-elbow","category":"body","question":"'the elbow'","answer":"el codo"},
{"id":"antebrazo-forearm","category":"body","question":"'the forearm'","answer":"el antebrazo"},
{"id":"dedo (de la mano)-finger","category":"body","question":"'the finger'","answer":"el dedo (de la mano)"},
{"id":"pecho-chest","category":"body","question":"'the chest'","answer":"el pecho"},
{"id":"corazón-heart","category":"body","question":"'the heart'","answer":"el corazón"},
{"id":"pulmón-lung","category":"body","question":"'the lung'","answer":"el pulmón"},
{"id":"pezon-nipple","category":"body","question":"'the nipple'","answer":"el pezon"},
{"id":"seno-breast","category":"body","question":"'the breast'","answer":"el seno"},
{"id":"estómago-stomach","category":"body","question":"'the stomach'","answer":"el estómago"},
{"id":"abdomen-abdomen","category":"body","question":"'the abdomen'","answer":"el abdomen"},
{"id":"muslo-thigh","category":"body","question":"'the thigh'","answer":"el muslo"},
{"id":"pie-foot","category":"body","question":"'the foot'","answer":"el pie"},
{"id":"tobillo-ankle","category":"body","question":"'the ankle'","answer":"el tobillo"},
{"id":"dedo (del pie)-toe","category":"body","question":"'the toe'","answer":"el dedo (del pie)"},
{"id":"músculo-muscle","category":"body","question":"'the muscle'","answer":"el músculo"},
{"id":"cabeza-head","category":"body","question":"'the head'","answer":"la cabeza"},
{"id":"frente-forehead","category":"body","question":"'the forehead'","answer":"la frente"},
{"id":"cara-face","category":"body","question":"'the face'","answer":"la cara"},
{"id":"ceja-eyebrow","category":"body","question":"'the eyebrow'","answer":"la ceja"},
{"id":"oreja-ear","category":"body","question":"'the ear'","answer":"la oreja"},
{"id":"boca-mouth","category":"body","question":"'the mouth'","answer":"la boca"},
{"id":"lengua-tongue","category":"body","question":"'the tongue'","answer":"la lengua"},
{"id":"garganta-throat","category":"body","question":"'the throat'","answer":"la garganta"},
{"id":"barbilla-chin","category":"body","question":"'the chin'","answer":"la barbilla"},
{"id":"muñeca-wrist","category":"body","question":"'the wrist'","answer":"la muñeca"},
{"id":"mano-hand","category":"body","question":"'the hand'","answer":"la mano"},
{"id":"espalda-back","category":"body","question":"'the back'","answer":"la espalda"},
{"id":"pierna-leg","category":"body","question":"'the leg'","answer":"la pierna"},
{"id":"rodilla-knee","category":"body","question":"'the knee'","answer":"la rodilla"},
{"id":"pantorrilla-calf (of the leg)","category":"body","question":"'the calf (of the leg)'","answer":"la pantorrilla"},
{"id":"piel-skin","category":"body","question":"'the skin'","answer":"la piel"},
{"id":"nalgas-buttocks","category":"body","question":"'the buttocks'","answer":"las nalgas"},
{"id":"abrigo-coat","category":"clothing","question":"'the coat'","answer":"el abrigo"},
{"id":"impermeable-raincoat","category":"clothing","question":"'the raincoat'","answer":"el impermeable"},
{"id":"suéter-sweater","category":"clothing","question":"'the sweater'","answer":"el suéter"},
{"id":"traje de baño-bathing suit","category":"clothing","question":"'the bathing suit'","answer":"el traje de baño"},
{"id":"pijama-pajamas","category":"clothing","question":"'the pajamas'","answer":"el pijama"},
{"id":"chaqueta-jacket","category":"clothing","question":"'the jacket'","answer":"la chaqueta"},
{"id":"camiseta-t-shirt","category":"clothing","question":"'the t-shirt'","answer":"la camiseta"},
{"id":"botas-boots","category":"clothing","question":"'the boots'","answer":"las botas"},
{"id":"sandalias-sandals","category":"clothing","question":"'the sandals'","answer":"las sandalias"},
{"id":"pantalones-pants","category":"clothing","question":"'the pants'","answer":"los pantalones"},
{"id":"pantalones cortos-shorts","category":"clothing","question":"'the shorts'","answer":"los pantalones cortos"},
{"id":"calcetines-socks","category":"clothing","question":"'the socks'","answer":"los calcetines"},
{"id":"zapatos-shoes","category":"clothing","question":"'the shoes'","answer":"los zapatos"},
{"id":"zapatillas-sneakers","category":"clothing","question":"'the sneakers'","answer":"los zapatillas"},
{"id":"negro-black","category":"color","question":"'black'","answer":" negro"},
{"id":"azul-blue","category":"color","question":"'blue'","answer":" azul"},
{"id":"marrón-brown","category":"color","question":"'brown'","answer":" marrón"},
{"id":"verde-green","category":"color","question":"'green'","answer":" verde"},
{"id":"gris-grey","category":"color","question":"'grey'","answer":" gris"},
{"id":"anaranjado-orange","category":"color","question":"'orange'","answer":" anaranjado"},
{"id":"rosado-pink","category":"color","question":"'pink'","answer":" rosado"},
{"id":"morado-purple","category":"color","question":"'purple'","answer":" morado"},
{"id":"rojo-red","category":"color","question":"'red'","answer":" rojo"},
{"id":"blanco-white","category":"color","question":"'white'","answer":" blanco"},
{"id":"amarillo-yellow","category":"color","question":"'yellow'","answer":" amarillo"},
{"id":"izquierda-left","category":"directions","question":"'left'","answer":" izquierda"},
{"id":"derecha-right","category":"directions","question":"'right'","answer":" derecha"},
{"id":"lejos-far","category":"directions","question":"'far'","answer":" lejos"},
{"id":"cerca-near","category":"directions","question":"'near'","answer":" cerca"},
{"id":"calle-street","category":"directions","question":"'street'","answer":" calle"},
{"id":"avenida-avenue","category":"directions","question":"'avenue'","answer":" avenida"},
{"id":"norte-north","category":"directions","question":"'north'","answer":" norte"},
{"id":"sur-south","category":"directions","question":"'south'","answer":" sur"},
{"id":"este-east","category":"directions","question":"'east'","answer":" este"},
{"id":"oeste-west","category":"directions","question":"'west'","answer":" oeste"},
{"id":"tenedor-fork","category":"eating","question":"'the fork'","answer":"el tenedor"},
{"id":"cuchillo-knife","category":"eating","question":"'the knife'","answer":"el cuchillo"},
{"id":"plato-plate","category":"eating","question":"'the plate'","answer":"el plato"},
{"id":"agua-water","category":"eating","question":"'the water'","answer":"el agua"},
{"id":"pan-bread","category":"eating","question":"'the bread'","answer":"el pan"},
{"id":"té-tea","category":"eating","question":"'the tea'","answer":"el té"},
{"id":"café-coffee","category":"eating","question":"'the coffee'","answer":"el café"},
{"id":"servilleta-napkin","category":"eating","question":"'the napkin'","answer":"la servilleta"},
{"id":"cuchara-spoon","category":"eating","question":"'the spoon'","answer":"la cuchara"},
{"id":"mantequilla-butter","category":"eating","question":"'the butter'","answer":"la mantequilla"},
{"id":"pimienta-pepper","category":"eating","question":"'the pepper'","answer":"la pimienta"},
{"id":"sal-salt","category":"eating","question":"'the salt'","answer":"la sal"},
{"id":"esposo-husband","category":"family","question":"'the husband'","answer":"el esposo"},
{"id":"cuñado-brother-in-law","category":"family","question":"'the brother-in-law'","answer":"el cuñado"},
{"id":"suegro-father-in-law","category":"family","question":"'the father-in-law'","answer":"el suegro"},
{"id":"yerno-son-in-law","category":"family","question":"'the son-in-law'","answer":"el yerno"},
{"id":"hijo-son","category":"family","question":"'the son'","answer":"el hijo"},
{"id":"padre-father","category":"family","question":"'the father'","answer":"el padre"},
{"id":"hermano-brother","category":"family","question":"'the brother'","answer":"el hermano"},
{"id":"abuelo-grandfather","category":"family","question":"'the grandfather'","answer":"el abuelo"},
{"id":"tío-uncle","category":"family","question":"'the uncle'","answer":"el tío"},
{"id":"sobrino-nephew","category":"family","question":"'the nephew'","answer":"el sobrino"},
{"id":"primo-cousin","category":"family","question":"'the cousin'","answer":"el primo"},
{"id":"hija-daughter","category":"family","question":"'the daughter'","answer":"la hija"},
{"id":"madre-mother","category":"family","question":"'the mother'","answer":"la madre"},
{"id":"hermana-sister","category":"family","question":"'the sister'","answer":"la hermana"},
{"id":"abuela-grandmother","category":"family","question":"'the grandmother'","answer":"la abuela"},
{"id":"tía-aunt","category":"family","question":"'the aunt'","answer":"la tía"},
{"id":"sobrina-niece","category":"family","question":"'the niece'","answer":"la sobrina"},
{"id":"esposa-wife","category":"family","question":"'the wife'","answer":"la esposa"},
{"id":"cuñada-sister-in-law","category":"family","question":"'the sister-in-law'","answer":"la cuñada"},
{"id":"suegra-mother-in-law","category":"family","question":"'the mother-in-law'","answer":"la suegra"},
{"id":"nuera-daughter-in-law","category":"family","question":"'the daughter-in-law'","answer":"la nuera"},
{"id":"niños-children","category":"family","question":"'the children'","answer":"los niños"},
{"id":"albaricoque-apricot","category":"fruit","question":"'the apricot'","answer":"el albaricoque"},
{"id":"limon-lemon","category":"fruit","question":"'the lemon'","answer":"el limon"},
{"id":"mango-mango","category":"fruit","question":"'the mango'","answer":"el mango"},
{"id":"melocotonte-peach","category":"fruit","question":"'the peach'","answer":"el melocotonte"},
{"id":"mélon-melon","category":"fruit","question":"'the melon'","answer":"el mélon"},
{"id":"fruta-fruit","category":"fruit","question":"'the fruit'","answer":"la fruta"},
{"id":"banana-banana","category":"fruit","question":"'the banana'","answer":"la banana"},
{"id":"frambuesa-raspberry","category":"fruit","question":"'the raspberry'","answer":"la frambuesa"},
{"id":"fresa-strawberry","category":"fruit","question":"'the strawberry'","answer":"la fresa"},
{"id":"manzana-apple","category":"fruit","question":"'the apple'","answer":"la manzana"},
{"id":"naranja-orange","category":"fruit","question":"'the orange'","answer":"la naranja"},
{"id":"pera-pear","category":"fruit","question":"'the pear'","answer":"la pera"},
{"id":"uva-grape","category":"fruit","question":"'the grape'","answer":"la uva"},
{"id":"cuarto de baño-bathroom","category":"house","question":"'the bathroom'","answer":"el cuarto de baño"},
{"id":"dormitorio-bedroom","category":"house","question":"'the bedroom'","answer":"el dormitorio"},
{"id":"comedor-dining room","category":"house","question":"'the dining room'","answer":"el comedor"},
{"id":"pasillo-hall","category":"house","question":"'the hall'","answer":"el pasillo"},
{"id":"salón-living room","category":"house","question":"'the living room'","answer":"el salón"},
{"id":"espejo-mirror","category":"house","question":"'the mirror'","answer":"el espejo"},
{"id":"jabón-soap","category":"house","question":"'the soap'","answer":"el jabón"},
{"id":"despertador-alarm clock","category":"house","question":"'the alarm clock'","answer":"el despertador"},
{"id":"colchón-mattress","category":"house","question":"'the mattress'","answer":"el colchón"},
{"id":"sábana-sheet","category":"house","question":"'the sheet'","answer":"el sábana"},
{"id":"lavaplatos-dishwasher","category":"house","question":"'the dishwasher'","answer":"el lavaplatos"},
{"id":"sartén-frying pan","category":"house","question":"'the frying pan'","answer":"el sartén"},
{"id":"microondas-microwave","category":"house","question":"'the microwave'","answer":"el microondas"},
{"id":"sillón-armchair","category":"house","question":"'the armchair'","answer":"el sillón"},
{"id":"reloj-clock","category":"house","question":"'the clock'","answer":"el reloj"},
{"id":"cocina-kitchen","category":"house","question":"'the kitchen'","answer":"la cocina"},
{"id":"bañera-bath","category":"house","question":"'the bath'","answer":"la bañera"},
{"id":"ducha-shower","category":"house","question":"'the shower'","answer":"la ducha"},
{"id":"cama-bed","category":"house","question":"'the bed'","answer":"la cama"},
{"id":"cocina-cooker","category":"house","question":"'the cooker'","answer":"la cocina"},
{"id":"sofá-sofa","category":"house","question":"'the sofa'","answer":"la sofá"},
{"id":"librería-bookcase","category":"house","question":"'the bookcase'","answer":"la librería"},
{"id":"carne-meat","category":"meat","question":"'the meat'","answer":"el carne"},
{"id":"res-beef","category":"meat","question":"'the beef'","answer":"el res"},
{"id":"puerco-pork","category":"meat","question":"'the pork'","answer":"el puerco"},
{"id":"pescado-fish","category":"meat","question":"'the fish'","answer":"el pescado"},
{"id":"ave-fowl ","category":"meat","question":"'the fowl '","answer":"el ave"},
{"id":"pollo-chicken","category":"meat","question":"'the chicken'","answer":"el pollo"},
{"id":"vaca-beef","category":"meat","question":"'the beef'","answer":"la vaca"},
{"id":"Enero-January","category":"months","question":"'January'","answer":" Enero"},
{"id":"Febrero-February","category":"months","question":"'February'","answer":" Febrero"},
{"id":"Marzo-March","category":"months","question":"'March'","answer":" Marzo"},
{"id":"Abril-April","category":"months","question":"'April'","answer":" Abril"},
{"id":"Mayo-May","category":"months","question":"'May'","answer":" Mayo"},
{"id":"Junio-June","category":"months","question":"'June'","answer":" Junio"},
{"id":"Julio-July","category":"months","question":"'July'","answer":" Julio"},
{"id":"Agosto-August","category":"months","question":"'August'","answer":" Agosto"},
{"id":"Septiembre-September","category":"months","question":"'September'","answer":" Septiembre"},
{"id":"Octubre-October","category":"months","question":"'October'","answer":" Octubre"},
{"id":"Noviembre-November","category":"months","question":"'November'","answer":" Noviembre"},
{"id":"Diciembre-December","category":"months","question":"'December'","answer":" Diciembre"},
{"id":"lunes-Monday","category":"weekdays","question":"'Monday'","answer":" lunes"},
{"id":"martes-Tuesday","category":"weekdays","question":"'Tuesday'","answer":" martes"},
{"id":"miércoles-Wednesday","category":"weekdays","question":"'Wednesday'","answer":" miércoles"},
{"id":"jueves-Thursday","category":"weekdays","question":"'Thursday'","answer":" jueves"},
{"id":"viernes-Friday","category":"weekdays","question":"'Friday'","answer":" viernes"},
{"id":"sábado-Saturday","category":"weekdays","question":"'Saturday'","answer":" sábado"},
{"id":"domingo-Sunday","category":"weekdays","question":"'Sunday'","answer":" domingo"}];
